### ISSUE TITLE
Fehler vom VPN-Status-Thread

### ISSUE THREAD

**Issue by malteb247** [komaflash/ffhb-sopel#4]
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/ec8or/.sopel/modules/ffhb.py", line 22, in monitor
    ffhb_gateway(bot, None, CHANNEL)
  File "/home/ec8or/.sopel/modules/ffhb.py", line 187, in ffhb_gateway
    status[vpn["name"]][service]["ipv4"] += vpn[service][0]["ipv4"]
KeyError: 'ipv4'
```

**Comment by genofire** [comment]
Keine Ahnung, woher das kommt.
Würde dieses Issue ignorieren, da mit #5 overall.json eingeführt wird und diese Codestelle entfällt.

**Comment by komaflash** [comment]
Liegt daran, das der key nicht immer da ist.

Muss mit nem if versehen werden.

**Comment by malteb247** [comment]
fixed
